version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - E:/DockerVolumes/chatwoot/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
      - bridge
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: sh -c "bundle exec rails db:chatwoot_prepare; bundle exec rails s -b 0.0.0.0 -p 3000"

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - E:/DockerVolumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"password\""]
    env_file: .env
    volumes:
      - E:/DockerVolumes/redis:/data
    ports:
      - '6379:6379'

  botpress:
    image: botpress/server:latest
    ports:
      - '3001:3000'
    volumes:
      - E:/DockerVolumes/botpress:/botpress/data

  bridge:
    image: douglara/chatwoot-botpress-bridge:1
    env_file: .benv
    ports:
      - '3002:3000'